[default]
cli_colors = true
port = 8000
# Generate secret_key with `openssl rand -base64 64`
secret_key = "mxfBGfBoBJRZr+zy3iylsmWbjk4x4rjkjNenyZNa0t7NFAZq1aFa35cwoiItpNV1G2JKchUtMdNRmaxFOXKi9g=="

[default.oauth.github]
provider = "GitHub"
client_id = "Ov23li8Qt3n1IcgNKjr8"
# DO NOT COMMIT OR PUBLISH THIS SECRET
client_secret = "e4af84e0d7fe2caa06d01c94e6096068818d154a"
redirect_uri = "http://127.0.0.1:8000/auth/github"
